on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Check and lint

jobs:
  movies-api:
    name: Movies Api (Go)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: apps/movies-api/go.mod
          cache-dependency-path: apps/movies-api/go.sum

      - name: Install Deps
        run: go mod download
        shell: bash
        working-directory: apps/movies-api

      - name: Download swaggo
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Swagger init
        run: make swagger
        working-directory: apps/movies-api

      - name: Lint
        uses: docker://morphy/revive-action:v2
        with:
          config: revive.toml
          pattern: apps/movies-api/...

      - name: Build
        run: make movies-api
        shell: bash
        working-directory: apps/movies-api
