name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/config/labels.yml
  workflow_dispatch:

permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/config/labels.yml
