on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

name: Test with Coverage

jobs:
  movies-api:
    name: Lint And Test Movies Api (Go)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: apps/movies-api/go.mod
          cache-dependency-path: apps/movies-api/go.sum

      - name: Install Deps
        run: go mod download
        shell: bash
        working-directory: apps/movies-api

      - name: Download swaggo
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Swagger init
        run: make swagger
        working-directory: apps/movies-api

      - name: Test
        run: |
          make coverage-ci
          cat coverage.out
        working-directory: apps/movies-api

      - uses: jandelgado/gcov2lcov-action@v1
        with:
          infile: coverage.out
          outfile: coverage.lcov
          working-directory: apps/movies-api

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: apps/movies-api/coverage.lcov
          language: Go
